### ISSUE TITLE
Can the source code work with uvision simulator?

### ISSUE THREAD

**Issue by sichunqin** [QuantumLeaps/modern-embedded-programming-course#1]
I try to use the uvision simulator to debug the project ( for example ,project 25). But fail due the following error:
*** error 65: access violation at 0x400FE070 : no 'write' permission
Looking forward to your reply! Thanks.

**Comment by sichunqin** [comment]
https://developer.arm.com/documentation/ka002225/latest
It seems that uvision doesn't support the device simulation as explained in the above web page.

**Comment by quantum-leaps** [comment]
Hi Sichun,
Thank you for your interest in the "Modern Embedded Systems Programming" course.

Not all lessons can be simulated. I'd have to look into this, but generally, projects that interact with the peripherals and use interrupts are tricky to simulate.

But simpler projects **can** be simulated in KEIL-MDK (with uVision IDE). Examples with the simulator have been very recently released and include lesson-01 through lesson lesson-03:
- https://github.com/QuantumLeaps/modern-embedded-programming-course/tree/main/lesson-01
- https://github.com/QuantumLeaps/modern-embedded-programming-course/tree/main/lesson-02
- https://github.com/QuantumLeaps/modern-embedded-programming-course/tree/main/lesson-03

--MMS

**Comment by sichunqin** [comment]
Understood. Thanks a lot for your great effort on the video training material!
